#%RAML 1.0
title: orderManagement



types:
  orderItems:
    properties:
      productId: string
      quantity: integer

/order:
  post:
    body:
      application/json:
        properties:
          cust_id: string
          list_of_items:
            type: array
            items: orderItems
    responses:
      200:
        body:
          application/json:
            example:
              {"message":"Order has been successfully placed"}
      422:
        body:
          application/json:
            example:
              {
                "message":"The required quantity for a product is not available in the inventory"
              }
            
/addCust:
  post:
    body:
      application/json:
        properties:
          cust_name: 
            type: string 
            required: true
          email:
            type: string
            required: true
          phone:
            type: string
            required: true
          city:
            type: string
            required: true
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"Thanks for registering into orderManagement"
              }
      409:
        body:
          application/json:
            example:
              {"message":"This email address is not available, use another email address"}



/product:
  get:
    queryParameters:
      category:
        type: string
        required: false
      maxPrice:
        type: number
        required: false
  post:
    body:
      application/json:
        properties:
          product_name:
           type: string
           required: true
          brand:
            type: string
            required: true
          category:
            type: string
            required: true
          stock:
            type: integer
            required: true
          price:
            type: number
            required: true
    responses:
      200:
        body:
          application/json:
            example:
              {"message":"Product added successfully, this is the product id"}
  /{productId}:
    get:
      description: get product details by productId
    put:
      body:
        application/json:
          properties:
            product_name:
              type: string
              required: true
            brand:
              type: string
              required: true
            category:
              type: string
              required: true
            stock:
              type: integer
              required: true
            price:
              type: number
              required: true
      responses:
        200:
          body:
            application/json:
              example:
                {"message":"Product updated successfully"}
    /restock:
      post:
        body:
          application/json:
            properties:
              quantity:
                type: number
                required: true




          
